language: perl6
perl6:
  - latest
install:
  - ( git clone git://github.com/shoichikaji/panda.git /tmp/panda && cd /tmp/panda && git checkout -b workaround origin/workaround && perl6 bootstrap.pl )
  - panda --notests installdeps .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -r t/
sudo: false
