language: perl6
perl6:
  - latest
install:
  - ( git clone git://github.com/shoichikaji/panda.git /tmp/panda && cd /tmp/panda && git checkout -b workaround origin/workaround && perl6 bootstrap.pl )
  - rakudobrew rehash
  - panda --notests installdeps .
script:
  - perl6 -MPanda::Builder -e 'Panda::Builder.build($*CWD)'
  - PERL6LIB=$PWD/blib/lib prove -e perl6 -r t/
sudo: false
