language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
script:
  - which perl && which prove && perl -V && prove --version
  - PERL6LIB=$PWD/lib prove -e perl6 -r t/
sudo: false
